TsubakiBotPad/pad-data-pipeline

media_pipelines/image_pull/PADTextureTool.py

When trimming is enabled, use the image size given in the data to crop images. For images with multiple frames (pixel cards) only the first frame will be kept.
This fix applies to:
1. Pixel images which were not split correctly [example1](https://d1kpnpud0qoyxf.cloudfront.net/media/portraits/03868.png) [example2](https://d1kpnpud0qoyxf.cloudfront.net/media/portraits/05741.png)
2. Bugged images with excess empty space at the bottom caused by random trash pixels [example1](https://d1kpnpud0qoyxf.cloudfront.net/media/portraits/05991.png) [example2](https://d1kpnpud0qoyxf.cloudfront.net/media/portraits/04609.png)

Fix incorrectly cropped MONS_ images

---

etl/pad/raw/skills/jp/active_skill_text.py
etl/pad/raw/skills/jp/enemy_skill_text.py

(optional PR, TR never liked these, but if you prefer then then :thumbsup:)

Take off JP safelocks

---

etl/pad/storage_processor/dimension_processor.py

```sql
INSERT INTO d_attributes (attribute_id, name) VALUES (5, 'Unused');
INSERT INTO d_attributes (attribute_id, name) VALUES (6, 'Null');
```
Run this before running the pipeline.

Add Unused and Null to DAttribute processor

---

etl/pad/storage/series.py
schema/mysql.sql

```sql
ALTER TABLE series ADD series_type text;
```

Add series_type column to series

---

etl/pad/storage/monster.py
schema/mysql.sql

```sql
ALTER TABLE monsters ADD COLUMN stackable tinyint(1) NOT NULL;
ALTER TABLE evolutions ADD COLUMN reversible tinyint(1) NOT NULL;
```
Related: https://github.com/TsubakiBotPad/pad-cogs/issues/721

Export reversible for evos and stackable for monsters

---

etl/pad/raw/skills/en/active_skill_text.py

Added 'remaining' to gravity skill text. Issue #93

---

etl/pad/storage/monster.py

This is to be merged after reverting the previous PR

Auto-update has_animation

---

etl/pad/raw_processor/merged_database.py

Suppress invalid LS/AS warnings on unobtainable cards

---

cronjobs/ilmina.sh
cronjobs/shared.sh

Export data for ilmina

---

etl/pad/common/dungeon_types.py

This is simply an irresponsible number of players

Add eight player dungeons

---

etl/pad/raw/bonus.py
etl/pad/storage_processor/schedule_processor.py

Haha 8p sucks so bad they had to invent a new bonus type to show how much it sucked

Add Dungeon Unavailable Popup

---

etl/pad/raw_processor/crossed_data.py
etl/pad/storage/monster.py
etl/pad/storage_processor/monster_processor.py
schema/mysql.sql

```sql
CREATE TABLE `alt_monsters` (
`alt_monster_id` int(11) NOT NULL,
`canonical_id` int(11) NOT NULL,
`active_skill_id` int(11) DEFAULT NULL,
`reg_date` date NOT NULL,
`is_alt` int(1) NOT NULL,
`tstamp` int(11) NOT NULL,
PRIMARY KEY (`alt_monster_id`),
KEY `tstamp_idx` (`tstamp`)
)
```

Add table alt_monsters

---

cronjobs/data_processor.sh

Now it sends the contents of the file rather than just the path to it

Add contents of file to human fix warning

---

etl/pad/raw/skills/leader_skill_info.py

This fixes the new skill params added for LS type 170 in evo Gorkaos (7233)

Add atk step to LSRainbowMultPlusShield

---

etl/pad/raw/skills/en/leader_skill_text.py
etl/pad/raw/skills/en/skill_common.py
etl/pad/raw/skills/leader_skill_info.py

Add scaling_attribute_match_text

---

etl/pad/raw/skills/en/leader_skill_text.py
etl/pad/raw/skills/en/skill_common.py
etl/pad/raw/skills/leader_skill_info.py
schema/mysql.sql

Add JP translation for scaling_attribute_match_text

---

etl/pad/storage/monster.py
schema/mysql.sql

Closes #140
Closes #84 
```sql
ALTER TABLE monsters ADD base_id int(11);
```

Add `base_id` column to `monsters`

---

cronjobs/export_data.sh

Reverts TsubakiBotPad/pad-data-pipeline#148

Revert "Add DADGUIDE_WAVE_DATA_FILE"

---

cronjobs/data_processor.sh
cronjobs/export_data.sh
cronjobs/run_loader.sh

Reverts TsubakiBotPad/pad-data-pipeline#147

Revert "Don't override files on exports"

---

etl/data_processor.py
etl/pad/common/utils.py
etl/pad/db/sql_item.py
etl/pad/storage/dungeon.py
etl/pad/storage/enemy_skill.py
etl/pad/storage/monster.py
schema/mysql.sql

```sql
CREATE TABLE `active_skills_na` (
`active_skill_id` int(11) NOT NULL,
`name_ja` text NOT NULL,
`name_en` text NOT NULL,
`name_ko` text NOT NULL,
`desc_ja` text NOT NULL,
`desc_en` text NOT NULL,
`desc_ko` text NOT NULL,
`turn_max` int(11) NOT NULL,
`turn_min` int(11) NOT NULL,
`tags` text NOT NULL,
`tstamp` int(11) NOT NULL,
PRIMARY KEY (`active_skill_id`),
KEY `tstamp_idx` (`tstamp`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE TABLE `awakenings_na` (
`awakening_id` int(11) NOT NULL AUTO_INCREMENT,
`monster_id` int(11) NOT NULL,
`awoken_skill_id` int(11) NOT NULL,
`is_super` tinyint(1) NOT NULL,
`order_idx` int(11) NOT NULL,
`tstamp` int(11) NOT NULL,
PRIMARY KEY (`awakening_id`),
KEY `monster_id_idx` (`monster_id`),
KEY `tstamp_idx` (`tstamp`),
KEY `awoken_skill_id_idx` …
```

Implement _na tables

---

etl/data_processor.py
etl/pad/storage/dungeon.py
etl/pad/storage/enemy_skill.py
etl/pad/storage/monster.py
etl/pad/storage_processor/monster_processor.py

Make NA tables NA-only instead of NA-priority

---

etl/pad/raw/skills/en/leader_skill_text.py
etl/pad/raw/skills/jp/leader_skill_text.py
etl/pad/raw/skills/leader_skill_info.py
etl/pad/storage_processor/series.json

Add LSComboBonusDamage, which fixes Hana LS

---

etl/pad/raw/skills/en/active_skill_text.py

Fix text for iron man

---

etl/pad/raw/skills/en/active_skill_text.py
etl/pad/raw/skills/jp/active_skill_text.py

Move create_unmatchable JP AS to JP folder

---

etl/data_processor.py

Fix bug with dungeon processor

---

etl/pad/storage/monster.py
etl/pad/storage/series.py
etl/pad/storage_processor/series_processor.py
schema/mysql.sql

```sql
CREATE TABLE `monster_series` (
`monster_series_id` int(11) NOT NULL,
`monster_id` int(11) NOT NULL,
`series_id` int(11) NOT NULL,
`priority` tinyint(1) NOT NULL,
`tstamp` int(11) NOT NULL,
PRIMARY KEY (`monster_id`, `series_id`),
KEY `tstamp` (`tstamp`),
CONSTRAINT `monster_series_fk_monster_id` FOREIGN KEY (`monster_id`) REFERENCES `monsters` (`monster_id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
CONSTRAINT `monster_series_fk_series_id` FOREIGN KEY (`series_id`) REFERENCES `series` (`series_id`) ON DELETE NO ACTION ON UPDATE NO ACTION
)
```

Add monster_series table

---

cronjobs/run_loader.sh

Fix Server option

---

etl/pad/raw/skills/leader_skill_info.py

Closes https://github.com/TsubakiBotPad/pad-cogs/issues/1321

Fix LSComboMultPlusShield

---

etl/data_processor.py
etl/pad/storage_processor/awoken_skill_processor.py

Closes #156
Idk why that's been open for so long

Change AwakeningProcessor to AwokenSkillProcessor

---

etl/pad/raw/skills/active_skill_info.py

Fix ASTimedEnemyAttrChange

---

etl/pad/raw/skills/en/active_skill_text.py
etl/pad/raw/skills/en/leader_skill_text.py
etl/pad/raw/skills/en/skill_common.py
etl/pad/raw/skills/leader_skill_info.py

Fix Composition Buff

---

etl/auto_dungeon_scrape.py
etl/pad/raw/bonus.py
etl/pad/raw_processor/merged_data.py
etl/pad/storage/schedule.py

```sql
UPDATE d_event_types SET name = "Unknown" WHERE event_type_id = 0;
INSERT INTO d_event_types (event_type_id, name) VALUES (1, "EXP Boost");
INSERT INTO d_event_types (event_type_id, name) VALUES (2, "Coin Boost");
INSERT INTO d_event_types (event_type_id, name) VALUES (3, "Drop Boost");
INSERT INTO d_event_types (event_type_id, name) VALUES (5, "Stamina Reduction");
INSERT INTO d_event_types (event_type_id, name) VALUES (6, "Dungeon");
INSERT INTO d_event_types (event_type_id, name) VALUES (8, "PEM Event");
INSERT INTO d_event_types (event_type_id, name) VALUES (9, "REM Event");
INSERT INTO d_event_types (event_type_id, name) VALUES (10, "PEM Cost");
INSERT INTO d_event_types (event_type_id, name) VALUES (11, "Feed XP Bonus Chance");
INSERT INTO d_event_types (event_type_id, name) …
```

Rework Schedule Items

---

etl/pad/raw/bonus.py

```sql
INSERT INTO d_event_types (event_type_id, name) VALUES (53, "8P Reward Table");
```

Add Bonus Type 53 (8P Reward Table)

---

etl/pad/raw/bonus.py
etl/pad/raw/extra_egg_machine.py
etl/pad/storage_processor/schedule_processor.py
etl/pad_data_pull.py

I'll change the name when it comes out in NA

Add Free Egg Machine

---

etl/pad/common/utils.py
etl/pad/raw/skills/active_skill_info.py
etl/pad/storage/monster.py
etl/pad/storage_processor/monster_processor.py

```sql
CREATE TABLE `transformations` (
`transformation_id` int(11) NOT NULL AUTO_INCREMENT,
`from_monster_id` int(11) NOT NULL,
`to_monster_id` int(11) NOT NULL,
`tstamp` int(11) NOT NULL,
PRIMARY KEY (`transformation_id`),
KEY `from_monster_id_idx` (`from_monster_id`),
KEY `to_monster_id_idx` (`to_monster_id`),
KEY `tstamp_idx` (`tstamp`),
CONSTRAINT `transformations_fk_from_monster_id` FOREIGN KEY (`from_monster_id`) REFERENCES `monsters` (`monster_id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
CONSTRAINT `transformations_fk_to_monster_id` FOREIGN KEY (`to_monster_id`) REFERENCES `monsters` (`monster_id`) ON DELETE NO ACTION ON UPDATE NO ACTION
);
CREATE TABLE `transformations_na` (
`transformation_id` int(11) NOT NULL AUTO_INCREMENT,
`from_monster_id` int(11) NOT NULL,
`to_monster_id` …
```

Add Transformation table

---

etl/pad/api/pad_api.py

Mostly intended for dungeons, but any request could in theory have the same issue; this retries on any invalid json

Retry on invalid JSON

---

etl/pad/raw/exchange.py
etl/pad/storage/exchange.py

```py
ALTER TABLE exchanges ADD COLUMN target_monster_amount int(11) NOT NULL;
UPDATE exchanges SET target_monster_amount = 1;
```

Add new target_monster_amount exchange field

---

cronjobs/data_processor.sh
etl/data_processor.py

This removes the --skip_long option and instead requires the DCP to be manually run via the --processors argument

Change how processors are handled

---

etl/pad/raw/skills/en/active_skill_text.py

Change awakening skill -> awoken skill

---

etl/pad/raw/skills/active_skill_info.py
etl/pad/raw/skills/en/active_skill_text.py
etl/pad/raw/skills/en/leader_skill_text.py
etl/pad/raw/skills/enemy_skill_info.py
etl/pad/raw/skills/jp/active_skill_text.py
etl/pad/raw/skills/jp/leader_skill_text.py
etl/pad/raw/skills/leader_skill_info.py

ASConditionalFloorThreshold
ESAbsorbThresholdBig
LSRarityThresholdBoost

Add new skill types

---

etl/pad/raw/skills/active_skill_info.py
etl/pad/raw/skills/en/active_skill_text.py
etl/pad/raw/skills/ja/active_skill_text.py
etl/pad/raw/skills/skill_common.py
etl/pad/raw_processor/crossed_data.py
etl/pad/storage/monster_skill.py
requirements.txt

```mysql
ALTER TABLE active_skills ADD COLUMN desc_ja_templated text NOT NULL AFTER desc_ja;
ALTER TABLE active_skills ADD COLUMN desc_en_templated text NOT NULL AFTER desc_en;
ALTER TABLE active_skills ADD COLUMN desc_ko_templated text NOT NULL AFTER desc_ko;
ALTER TABLE active_parts ADD COLUMN desc_ja_templated text NOT NULL AFTER desc_ja;
ALTER TABLE active_parts ADD COLUMN desc_en_templated text NOT NULL AFTER desc_en;
ALTER TABLE active_parts ADD COLUMN desc_ko_templated text NOT NULL AFTER desc_ko;
ALTER TABLE active_skills_na ADD COLUMN desc_ja_templated text NOT NULL AFTER desc_ja;
ALTER TABLE active_skills_na ADD COLUMN desc_en_templated text NOT NULL AFTER desc_en;
ALTER TABLE active_skills_na ADD COLUMN desc_ko_templated text NOT NULL AFTER desc_ko;
ALTER TABLE active_parts_na …
```

Add desc_lang_templated to active_skills and active_parts 

---

etl/pad/storage/monster_skill.py

```mysql
ALTER TABLE active_skills CHANGE desc_ja_templated desc_templated_ja text NOT NULL;
ALTER TABLE active_skills CHANGE desc_en_templated desc_templated_en text NOT NULL;
ALTER TABLE active_skills CHANGE desc_ko_templated desc_templated_ko text NOT NULL;
ALTER TABLE active_skills CHANGE desc_ja_official desc_official_ja text NOT NULL;
ALTER TABLE active_skills CHANGE desc_en_official desc_official_en text NOT NULL;
ALTER TABLE active_skills CHANGE desc_ko_official desc_official_ko text NOT NULL;
ALTER TABLE active_skills_na CHANGE desc_ja_templated desc_templated_ja text NOT NULL;
ALTER TABLE active_skills_na CHANGE desc_en_templated desc_templated_en text NOT NULL;
ALTER TABLE active_skills_na CHANGE desc_ko_templated desc_templated_ko text NOT NULL;
ALTER TABLE active_skills_na …
```

Change desc_lang_type to desc_type_lang

---

etl/pad/raw/skills/active_skill_info.py
etl/pad/storage/monster_skill.py
etl/pad/storage_processor/monster_processor.py

If I have to write another huge wall of SQL again I'm going to cry
```mysql
ALTER TABLE active_skills ADD COLUMN compound_skill_type_id int(11) NOT NULL AFTER active_skill_id;
ALTER TABLE active_skills ADD CONSTRAINT active_skills_fk_compound_skill_type_id FOREIGN KEY (compound_skill_type_id) REFERENCES d_compound_skill_types (compound_skill_type_id);
ALTER TABLE active_skills MODIFY COLUMN desc_templated_ja text NOT NULL AFTER desc_ko;
ALTER TABLE active_skills MODIFY COLUMN desc_templated_en text NOT NULL AFTER desc_templated_ja;
ALTER TABLE active_skills MODIFY COLUMN desc_templated_ko text NOT NULL AFTER desc_templated_en;
ALTER TABLE active_skills MODIFY COLUMN desc_official_ja text NOT NULL AFTER desc_templated_ko;
ALTER TABLE active_skills MODIFY COLUMN desc_official_en text NOT …
```

Fix Active Skills

---

etl/pad/raw/skill.py
etl/pad/raw/skills/active_skill_info.py
etl/pad/storage/monster_skill.py

```mysql
ALTER TABLE active_skills ADD COLUMN cooldown_turns_max int(11) NOT NULL AFTER desc_official_ko;
ALTER TABLE active_skills ADD COLUMN cooldown_turns_min int(11) NOT NULL AFTER cooldown_turns_max;
ALTER TABLE active_subskills ADD COLUMN cooldown int(11) NOT NULL AFTER desc_templated_ko;
```

Export cooldowns

---

etl/pad/raw/skills/active_skill_info.py
etl/pad/storage/monster_skill.py

Fix subskills

---

etl/pad/common/pad_util.py
etl/pad/raw_processor/crossed_data.py
etl/pad/raw_processor/merged_data.py
etl/pad/raw_processor/merged_database.py
etl/pad/storage/dungeon.py
etl/pad/storage/monster.py
etl/pad/storage_processor/dungeon_processor.py
etl/pad/storage_processor/monster_processor.py

This also fixes some issues with alt_monsters

Adjust monster ids for server overlaps

---

etl/pad/storage/encounter.py
etl/pad/storage_processor/dungeon_content_processor.py
web/admin_api_server.py

```mysql
ALTER TABLE encounters CHANGE defence defense bigint(20);
```

Use the American spelling of defense

---

etl/pad/raw/skills/monster_skill_test.py

This adds the option for multiple output languages and a skill_id search

Add to skill test

---

etl/pad/raw/skills/en/active_skill_text.py
etl/pad/raw/skills/ja/active_skill_text.py

Reference: 5235 - Detective of the Time Labyrinth, Shelling Ford

Updated team_target_stat_change

---

etl/pad/raw/skills/active_skill_info.py
etl/pad/raw/skills/en/active_skill_text.py
etl/pad/raw/skills/ja/active_skill_text.py

Reference: 8614 - 生物調査の専門家・カイト

Added ASRandomChangeMonster

---

etl/pad/raw/skills/active_skill_info.py
etl/pad/raw/skills/en/active_skill_text.py
etl/pad/raw/skills/ja/active_skill_text.py
etl/pad/storage/monster.py
etl/pad/storage_processor/monster_processor.py

Add transform_ids AND add context to active skills

---

etl/pad/storage/monster.py
etl/pad/storage_processor/monster_processor.py

```mysql
ALTER TABLE monsters ADD COLUMN group_id int(11) NOT NULL;
ALTER TABLE monsters_na ADD COLUMN group_id int(11) NOT NULL;
```

Add group_id to monsters

---

etl/data_processor.py
etl/pad/storage_processor/series_processor.py

Since https://github.com/TsubakiBotPad/pad-cogs/pull/1678, this will be handled by crud cog in Tsubaki.

Remove pipeline series processing

---

etl/pad/raw/skills/en/active_skill_text.py

Fix random transform skill fraction displays

---

etl/pad/raw/skills/active_skill_info.py
etl/pad/raw/skills/en/active_skill_text.py
etl/pad/raw/skills/ja/active_skill_text.py
etl/pad/raw/skills/skill_common.py
etl/pad/storage/monster_skill.py

```mysql
ALTER TABLE active_subskills ADD COLUMN board_65 CHAR(30) AFTER desc_templated_ko;
ALTER TABLE active_subskills ADD COLUMN board_76 CHAR(42) AFTER board_65;
ALTER TABLE active_subskills_na ADD COLUMN board_65 CHAR(30) AFTER desc_templated_ko;
ALTER TABLE active_subskills_na ADD COLUMN board_76 CHAR(42) AFTER board_65;
```

Add board shapes to active subskills

---

cronjobs/dungeon_scraper.sh
cronjobs/pull_data.sh
etl/auto_dungeon_scrape.py
etl/pad/raw/bonus.py
etl/pad/raw_processor/merged_data.py
etl/pad/raw_processor/merged_database.py
etl/pad/storage/schedule.py
etl/pad_data_pull.py

```mysql
CREATE TABLE schedule_old AS SELECT * FROM schedule;
DELETE FROM schedule WHERE group_name = 'green' OR group_name = 'blue';
ALTER TABLE schedule DROP COLUMN group_name;
```

Remove starter group from scheduled events

---

etl/pad/db/sql_item.py
etl/pad/raw/skills/active_behaviors.py
etl/pad/raw/skills/active_skill_info.py
etl/pad/raw/skills/skill_common.py
etl/pad/storage/latent_skill.py
etl/pad/storage/monster_skill.py

```mysql
ALTER TABLE active_subskills ADD COLUMN behavior JSON AFTER active_subskill_id;
ALTER TABLE active_parts ADD COLUMN behavior JSON AFTER active_part_id;
ALTER TABLE active_parts ADD COLUMN raw_behavior JSON AFTER active_skill_type_id;
```

Add ASBehaviors

---

etl/pad/raw/skills/active_skill_info.py
etl/pad/raw/skills/en/active_skill_text.py
etl/pad/raw/skills/ja/active_skill_text.py

Update spinner active

---

etl/pad/raw/card.py
etl/pad/storage/monster.py

```sql
ALTER TABLE monsters ADD bgm_id int(11) AFTER orb_skin_id;
```

Add bgm_id to monsters

---

etl/misc/azurlane_image_download.py

Wiki endpoint changed urls + renamed a data field

Fixing Azur scraper

---

etl/pad/raw/dungeon.py
etl/pad/storage/dungeon.py

i hate gungho i hate gungho i hate gungho i hate gungho

Fix Fixed Team Monsters

---

cronjobs/media/update_image_files.sh
media_pipelines/assets/PADHQImageDownload.py

Do HQ images last

---

etl/egg_processor.py
etl/pad/db/db_util.py
etl/pad/db/sql_item.py
etl/pad/storage/awoken_skill.py
etl/pad/storage/dungeon.py
etl/pad/storage/egg_machine.py
etl/pad/storage/egg_machines_monsters.py
etl/pad/storage/encounter.py
etl/pad/storage/enemy_skill.py
etl/pad/storage/exchange.py
etl/pad/storage/latent_skill.py
etl/pad/storage/monster.py
etl/pad/storage/monster_skill.py
etl/pad/storage/purchase.py
etl/pad/storage/schedule.py
etl/pad/storage/series.py
etl/pad/storage/skill_tag.py
etl/pad/storage_processor/egg_machine_processor.py

```sql
DELETE FROM evolutions WHERE evolution_id IN (SELECT * FROM (SELECT e1.evolution_id FROM evolutions e1 JOIN evolutions e2 USING (to_id) WHERE e1.tstamp < e2.tstamp) t);
ALTER TABLE evolutions MODIFY COLUMN evolution_id int(11);
ALTER TABLE evolutions DROP PRIMARY KEY;
ALTER TABLE evolutions ADD CONSTRAINT PRIMARY KEY (to_id);
ALTER TABLE evolutions DROP COLUMN evolution_id;
DELETE FROM evolutions_na WHERE evolution_id IN (SELECT * FROM (SELECT e1.evolution_id FROM evolutions_na e1 JOIN evolutions_na e2 USING (to_id) WHERE e1.tstamp < e2.tstamp) t);
ALTER TABLE evolutions_na MODIFY COLUMN evolution_id int(11);
ALTER TABLE evolutions_na DROP PRIMARY KEY;
ALTER TABLE evolutions_na ADD CONSTRAINT PRIMARY KEY (to_id);
ALTER TABLE evolutions_na DROP COLUMN evolution_id;
ALTER TABLE …
```

Add multikeys to SQL Items

---

etl/pad/storage/monster.py

```mysql
ALTER TABLE MONSTERS MODIFY COLUMN monster_no_jp int(11);
ALTER TABLE MONSTERS MODIFY COLUMN monster_no_na int(11);
ALTER TABLE MONSTERS MODIFY COLUMN monster_no_kr int(11);
UPDATE monsters SET monster_no_jp = NULL WHERE on_jp = 0;
UPDATE monsters SET monster_no_na = NULL WHERE on_na = 0;
UPDATE monsters SET monster_no_kr = NULL WHERE on_kr = 0;
```

Keep monster_no_<server> null if not in server
